### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by simonezambonim** [nabeel-oz/qlik-py-tools#100]
**Describe the bug**
Hi Nabeel, I have been trying to install the environment and required packages but I always get an error. 

At first, it seemed to be related to pystan, required for prophet.
When I installed another env with only prophet and its dependencies I had to do one step more to make it work:
```
conda install libpython m2w64-toolchain -c msys2
```
As indicated [here](https://pystan.readthedocs.io/en/latest/windows.html)

However, after removing from the Qlik-Py-init.bat these both lines
```
pip install pystan==2.17
pip install fbprophet==0.4.post2
```
I keep getting errors from other packages even scikit-learn, one part of the error states
```
Partial import of sklearn during the build process.
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
```

Errors packages:
prophet 
scikit-image
scikit-learn
spacy
tensorflow

**Environment:**
 - OS [Windows 10 - local]

**Comment by nabeel-oz** [comment]
The errors look like they are due to a missing C++ compiler. On Windows the most reliable option is to use MS Visual Studio Build Tools which is one of the installation steps here: https://github.com/nabeel-oz/qlik-py-tools/blob/master/README.md#installation

The current release does have one error that shows up during installation, but that is for the skater library and can be ignored. I need to replace that library as it is problematic.

**Comment by simonezambonim** [comment]
Thank you, Nabeel! First I want to thank you for sharing your great work with the community!
I have followed the steps in the Introducton you've mentioned but I couldn't make it work right away, I had to build my own environment through Anaconda prompt  (it has to do with the c++ compiler) and add gcc to my environment variables path.
I'm still figuring out some packages errors! In the meanwhile, I gotta play with some of them at least! 
Thank you again!
