### ISSUE TITLE
ERROR: Could not build wheels for bottleneck which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by peterltn** [nabeel-oz/qlik-py-tools#102]
**Describe the bug**
When I clicked the Qlik-Py-Init.bat, it shows below error message.

**Screenshots**
If applicable, add screenshots from `Qlik-Py-Init` to show the full error message.
![image](https://user-images.githubusercontent.com/31384243/83124293-99c73100-a108-11ea-91a7-b579bb8f23b7.png)
![image](https://user-images.githubusercontent.com/31384243/83124317-a3509900-a108-11ea-88d5-154224515756.png)
![image](https://user-images.githubusercontent.com/31384243/83124328-a8154d00-a108-11ea-9118-de93ca3bbee3.png)

**Environment:**
 - Windows 10
 - Qlik Sense Desktop
 - SSE Version v8.0

**Comment by nabeel-oz** [comment]
@peterltn , I see a similar issue posted on the HDBSCAN git repo [here](https://github.com/scikit-learn-contrib/hdbscan/issues/293). This seems to be caused by missing C++ compilers, so please check you have the MS Visual Studio Build Tools installed with the packages described in the installation guide: https://github.com/nabeel-oz/qlik-py-tools#installation

**Comment by peterltn** [comment]
It works, thanks.
