### ISSUE TITLE
Classification (Logistic Regression) 

### ISSUE THREAD

**Issue by PlupClub** [nabeel-oz/qlik-py-tools#34]
Hey @nabeel-oz, hope you're doing well. 
I'm trying to reverse engineer the Qonnections machine learning sample (appointment no-shows), using different data. While the SSE seems to work fine when I do a load for the original sample app, on the new app it gives me the following error: 

error: Connector reply error: grpc::StatusCode::UNKNOWN: 'Exception iterating responses: local variable 'scale_df' referenced before assignment'

This happens in the Model Training and Testing sheet (I checked using the exit script). 

Here is the actual code I have: 
![Code 1](https://user-images.githubusercontent.com/36251558/60866195-5ee4b200-a245-11e9-8c7d-09d899d1f4bd.PNG)
![Code 2](https://user-images.githubusercontent.com/36251558/60866197-5ee4b200-a245-11e9-8216-83265f2fc5a3.PNG)
![Code 3](https://user-images.githubusercontent.com/36251558/60866199-5ee4b200-a245-11e9-9c8d-83d431b1bf50.PNG)
![Code 4](https://user-images.githubusercontent.com/36251558/60866201-5f7d4880-a245-11e9-887c-618cff7cce40.PNG)

I'm really new to both Qlik and Python, so I apologize if it's something elementary I'm getting stuck on. Please let me know if I can provide any more information. Thank you!

**Comment by nabeel-oz** [comment]
Hi @PlupClub,

This is probably because of incorrect feature definitions. You have set the `Variable_Type` field as target for all the features. You should have just one target field and the rest should be set to `feature`. More info [here](https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/scikit-learn.md#preparing-feature-definitions).

But there is another issue that you are scaling your target. If you're using classification the target should be a discrete value which we shouldn't need to scale. You can set the feature strategy as `none`. If it is a continuous variable you should be using regression.

**Comment by PlupClub** [comment]
Thanks for your quick response!
The "scaling" and "target" instead of "feature" were hasty copy-paste errors; I've tried with the strategy set to none, and with the correct variable types, but I still get the same error.

**Comment by nabeel-oz** [comment]
@PlupClub , Can you please paste a screenshot of the full stack trace of the error from the terminal where you are running the SSE? I'll need to see exactly where the error occurs. Also, I'd like to see your updated `feature_definitions` table and the arguments that you have set in the `MODEL_INIT` table.

**Comment by PlupClub** [comment]
Nabeel, Sure, I've attached them. 
This is my second time writing the code for this, I got the feature definitions right the first time but still got the error, I think I made a mistake copying them over the second time. 
The target variable is just a yes/no categorical, I converted it to boolean (-1,0), and it is a string right now. Every predictor is an integer. 
![Uploading Feature Definitions.PNG…
![Model_Init](https://user-images.githubusercontent.com/36251558/60890356-c0724400-a278-11e9-8b54-ace30c10262b.PNG)
![Qlik Sense Debug](https://user-images.githubusercontent.com/36251558/60890357-c0724400-a278-11e9-8727-ee8f0158345a.PNG)





![Error Trace 1](https://user-images.githubusercontent.com/36251558/60890274-9c166780-a278-11e9-8058-017f7130e2de.PNG)
![Error Trace 2](https://user-images.githubusercontent.com/36251558/60890353-bfd9ad80-a278-11e9-9b07-62fd49357cbc.PNG)

**Comment by nabeel-oz** [comment]
Aha, it looks like there are two things going wrong here. The first is that you have found a bug (which I will fix in the next release). But the second is that you shouldn't be hitting the bug if we get the feature definitions right.

You now have the `Feature_Strategy` as `none` for all your features. Generally you should be scaling numerical data so that the model is not confused by features having different range of values. Keep it as `none` for your target, but change the rest to `scaling`.

Also, are all of your features really integers? For e.g. I would have expected CGPA to be a float. You'll need to provide the correct data types in the feature definitions table so that the SSE knows how to pre-process the data.

**Comment by PlupClub** [comment]
Hey Nabeel, 
you were absolutely right. I'm glad my silliness helped in some small way. Closing the issue, thank you
