### ISSUE TITLE
Clustering - Index contains duplicate values, cannot reshape

### ISSUE THREAD

**Issue by LiteralToddChavez** [nabeel-oz/qlik-py-tools#35]
I'm using the clustering sample app, but not able to recreate it. I've tried to make my dataset as similar to the sample as possible, but I'm not being able to diagnose my mistake. I've attached my data load script and the error trace. I only have one table (I prepared the data to look similar to the victoria dataset in Excel), and I've posted a sample of the data: 

![trace1](https://user-images.githubusercontent.com/53191385/61653989-25965280-acd9-11e9-9c4f-b6fabb9e8c44.PNG)
![trace2](https://user-images.githubusercontent.com/53191385/61654000-2929d980-acd9-11e9-8156-44b6982a4803.PNG)

![script1](https://user-images.githubusercontent.com/53191385/61654004-2b8c3380-acd9-11e9-9bcc-633eb0c640ea.PNG)
![script2](https://user-images.githubusercontent.com/53191385/61654015-2f1fba80-acd9-11e9-88a8-c9cda83cae12.PNG)

![DataSample](https://user-images.githubusercontent.com/53191385/61654021-30e97e00-acd9-11e9-8154-658700429839.PNG)

![error](https://user-images.githubusercontent.com/53191385/61654577-5925ac80-acda-11e9-9496-4bd59767c040.PNG)

(error occurs on line 21 of the cluster 1 tab)
I created the ca_iucr_desc field to create one unique field, but it doesn't seem to work. I tried adding an index to my table and that didn't either.

**Comment by nabeel-oz** [comment]
@LiteralToddChavez , are you sure that SubField expression in your `TempInputsTwoDims` table is what you want? For example, it will transform the descriptions `AGGRAVATED: HANDGUN` and `AGGRAVATED: OTHER` to `AGGRAVATED:` and you'll end up with two rows for this `SubGroup` for each `CA`. The final input to the clustering algorithm should have one unique row for each item that you are trying to cluster; `CA` in this case.

I think using the `description` or `iucr` field for the sub-grouping would make more sense. The other option is to use a `Group By` clause so that rates are aggregated by your key dimension and subgroup.

**Comment by LiteralToddChavez** [comment]
Hey @nabeel-oz, Thank you, that helped!
