### ISSUE TITLE
NER crash during Association_Rules

### ISSUE THREAD

**Issue by lachlanwwells** [nabeel-oz/qlik-py-tools#41]
Hi Nabeel,

Thanks for your hard work on this.
We are currently running the docker image pulled from the hub on a DigitalOcean Ubuntu/Docker server but when running the NER script (using just a single chapter from the LOTR QVDs), once it finishes the epoch loop, and gets to execute function 33 - Association_Rules, it continues on for approx 5 minutes and then causes the docker container to crash and restart.

Any tips on how to find logs/if there is anything you an think of that is causing this?
Server resources don't seem to be stressed so unsure what it could be...

Thanks again!

**Comment by nabeel-oz** [comment]
Hi Lachlan, 

Does your container have any resource limitations? If it does it could be killed even while the system has enough resources.

For the SSE logs you can store them to a volume or a bind mount so you can view them after a container is lost. 

```
# Store log files to a bind mount on the host machine
docker run -p 50055:50055 -it -v ~/Documents/logs:/qlik-py-tools/core/logs nabeeloz/qlik-py-tools
```

But if it's a resource issue you'll need to investigate why the docker container was killed. Some help on that [here](https://stackoverflow.com/questions/38112968/how-to-know-the-reason-why-a-docker-container-exits).

I tested the app by just running the association rules function on the full dataset. You can do this by changing line 5 in the section `Apriori Association Rules`:

```
// We use a condition to control if the SSE needs to be called or if we just use a QVD file from the last execution
LET vApriori = 0;
```

Using `docker stats` I saw a maximum memory usage of 238 MB while the function was being executed:
![image](https://user-images.githubusercontent.com/21298843/62746410-c1261200-ba92-11e9-87a8-cc2d4bec12b1.png)

The load completed in 2mins and 28 secs:
![image](https://user-images.githubusercontent.com/21298843/62746427-d13df180-ba92-11e9-9df6-4d62a315fd1e.png)

**Comment by lachlanwwells** [comment]
Hi Nabeel,

Thanks for the quick response!
I have completed the steps as you mention and it works successfully when running only the Apriori function
It seems to only crash when running all the functions in the app (both NEF and Apriori)

The error message displayed in the console is:

[libprotobuf FATAL google/protobuf/wire_format.cc:740] CHECK failed: (output->ByteCount()) == (expected_endpoint): : Protocol message serialized to a size different from what was originally expected.  Perhaps it was modified by another thread during serialization?
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (output->ByteCount()) == (expected_endpoint): : Protocol message serialized to a size different from what was originally expected.  Perhaps it was modified by another thread during serialization?

The memory usage is similar to yours, 280mb

**Comment by nabeel-oz** [comment]
Hi Lachlan, 

I just ran the app with all functions successfully, so I can't reproduce the issue on my Ubuntu VM. Running all the functions took up ~530MB of memory and the load ran for ~10 mins. 

The error you are getting has to do with the gRPC protocol rather than a specific point of failure in one of the functions. So I can't guess at what's going wrong.

From the SSE logs are you able to see at what point the crash occurs? Two of the functions have debugging turned off, but if you search for `debug=false` in the load script and change it to `debug=true` before you run the full load you should be able to trace exactly where things go awry.

Also, you may know this, but you should be able to get your killed container's ID with `docker ps -a` and then do a `docker inspect <container id>` to see if there is an exit code that helps.

**Comment by nabeel-oz** [comment]
Closing this issue as it has been inactive for ~3 months.
