### ISSUE TITLE
One Feature Short (Connector reply error: grpc::StatusCode::UNKNOWN: 'Exception iterating responses: 11 columns passed, passed data had 12 columns')

### ISSUE THREAD

**Issue by SyedAlamdar** [nabeel-oz/qlik-py-tools#42]
Hi Nabeel,

I am getting the following error. Funny thing is that that are moments when I don't get this error and it goes thought to a successful load.  I first thought that this could be due to my data but I tried fixing this in the load script (you will see one you load the file).

![image](https://user-images.githubusercontent.com/34166232/62839755-dc844f00-bc43-11e9-8b96-5571d97d4836.png)
![image](https://user-images.githubusercontent.com/34166232/62839764-02115880-bc44-11e9-8169-ca42d2f00d58.png)

My data and the structured data with the Qlik App is part of the ticket. I am using publically available data so anyone who is doing this is most welcome to dive in. 

 My Files:
[winequality-white-setup.xlsx](https://github.com/nabeel-oz/qlik-py-tools/files/3490459/winequality-white-setup.xlsx)
[ML Training.zip](https://github.com/nabeel-oz/qlik-py-tools/files/3490461/ML.Training.zip)

Another fun fact, when this runs, the best results I get are in lower 50%s. Any tips to improve those will also help.

**Comment by nabeel-oz** [comment]
@SyedAlamdar , The error you should first consider is the "missing 1 required positional argument 'estimators" message. You can pass the `debug=true` argument in your `vExecutionArgs` variable to find out where this error occurs. I see this error is for the VotingClassifier estimator, which is an ensemble algorithm and requires a list of estimators that it will use for voting. 

Currently it's not possible to pass a list of tuples in the hyperparameters as is required for this classifier, so you should just take it out from your list of estimators. Just looking at the number of estimators you are using, I'd suggest to pick a few from the different methods and try them out first. 

Since this is a public dataset, you can search for techniques used to get the best results. In most problems you need to derive new features from the base data to get better predictions. The input features will often have a much bigger impact on your model's accuracy than the type of estimator used.

**Comment by SyedAlamdar** [comment]
Got it.
