### ISSUE TITLE
Qlik-Py-Init Errors

### ISSUE THREAD

**Issue by Lobmeister165** [nabeel-oz/qlik-py-tools#45]
I am encountering errors when I run Qlik-Py-Init.bat file and then when running Qlik-Py-Start.bat.
Please see the screenshots attached.
I have installed Python 3.6.8 and MS C++ compiler as instructed before running Qlik-Py-Tools bat files
Qlik Sense accordingly does not recognize the PyTools functions in expressions containing them

Thanks in advance for a solution

![QlikPyToolsInit_ErrorCode1](https://user-images.githubusercontent.com/21658528/64529476-e3fe4d00-d302-11e9-941a-acbf76b7bcae.png)

![QlikPyToolsInit_ErrorCode2](https://user-images.githubusercontent.com/21658528/64529504-f4162c80-d302-11e9-8c01-a962715253aa.png)

![QlikPyToolsStart_ErrorCode](https://user-images.githubusercontent.com/21658528/64529514-f9737700-d302-11e9-9466-3f3219d039d5.png)

**Comment by fernandohHenri** [comment]
I also have the same problem.

**Comment by nabeel-oz** [comment]
This looks like a duplicate of issue #38. I suspect you both have the 32bit version of Python installed, as the error occurs because of the standard Python module `enum` missing an attribute in the 32bit version. This is just the tip of the iceberg as the 32bit version will give you various issues. 

You'll need to uninstall Python and reinstall the 64 bit version.

https://www.python.org/downloads/release/python-368/
Use the `Windows x86-64 executable installer` or `Windows x86-64 web-based installer`.

**Comment by Lobmeister165** [comment]
thank you so much - all working fine now with 64-bit Python :-)
