### ISSUE TITLE
Prophet Not Showing Results

### ISSUE THREAD

**Issue by aljamo01** [nabeel-oz/qlik-py-tools#54]
Hi there,

After I managed to get C++ compiler and pystan working I am still not seeing results from the Prophet function on Qlik. Note that all other functions work perfectly. Here is what I get when I execute the function. 
![Untitled](https://user-images.githubusercontent.com/32106301/66051695-e5332c00-e4f4-11e9-84da-ee965459484a.png)

**Comment by nabeel-oz** [comment]
Hi, 

Are you passing the future periods to the function as well i.e future dates with null values for the count? This is required to get back a forecast for those future dates. 

This is mentioned in the documentation here: https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Prophet.md

**Comment by aljamo01** [comment]
Yes. the function doesn't seem to work even though it shows that it was executed.
![Untitled1](https://user-images.githubusercontent.com/32106301/66080839-7eca0000-e52c-11e9-8359-5439c8e74c06.png)

**Comment by nabeel-oz** [comment]
Can you change the function arguments to `freq=M, debug=true` and show me the log from the SSE terminal?

**Comment by aljamo01** [comment]
Here..
![Untitled3](https://user-images.githubusercontent.com/32106301/66081722-357ab000-e52e-11e9-9ecc-ca6aa6ff9268.png)

**Comment by aljamo01** [comment]
![Untitled4](https://user-images.githubusercontent.com/32106301/66082152-1d576080-e52f-11e9-9e02-cc71f312b006.png)

**Comment by nabeel-oz** [comment]
From that we can see that the request does not contain future periods and the input data frame ends up empty. To investigate why, you should change the table in your app to use the same dimension and measure being passed to Prophet. Check that you're passing a date with a numerical representation rather than a string to Prophet.

**Comment by aljamo01** [comment]
I wonder why would the future periods not get passed.. I am using the same dimension and it is numerical. I haven't changed any of the script from the hands-on forecasting app but I still get those results. 
![Untitled5](https://user-images.githubusercontent.com/32106301/66083012-0a459000-e531-11e9-851c-c3653379cd1e.png)

**Comment by nabeel-oz** [comment]
The `Actual` measure that you're using in your table is not producing the same result as `Sum(Attendances)` in your Prophet expression. From the request data frame in the SSE logs I can see that you have actual values until Dec 2018. 

I suppose you have reloaded the app from a source file with additional data, but did not extend the future periods. You can either add the future periods in the source file or use the load script snippet in issue #52. You may also want to update the Actual measure as it was fixed to only show values before July 2018. 

Also, you can just use [Sample_App_Forecasting_Simple.qvf](https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Sample_App_Forecasting_Simple.qvf) which comes with the latest data and future periods.

**Comment by kutkin54** [comment]
Hi Nabeel, actually if you do not mind, could you kindly provide us the raw excel and csv files that are required to specifically used in the LOAD script? We can make them accessible, right? I understand that you do provide the links, but they are not pointing to the required file if you check again. I mean some of the filename mentioned in the LOAD script cannot be found in the two links provided by you at all. For example, I cannot find the source file for PERSON.csv or VEHICLE.csv in the two links provided. I really hope you understand because I find it quite hard to learn to reproduce the forecasting chart because I could not reload the data models, add new future values, and then use new data source that is suitable for your script to read it.

**Comment by nabeel-oz** [comment]
@kutkin54 , the Sample_App_Prophet.qvf that you are using only applies the forecasting at the front-end so does not need to be reloaded to understand how the expressions work. This app is meant to be understood using the documentation under [Use Prophet with your own app](https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Prophet.md#use-prophet-with-your-own-app). 

However, you can reload the [Sample_App_Forecasting_Simple.qvf](https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Sample_App_Forecasting_Simple.qvf) as it comes with the data source attached to the app and also available [here](https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/VIC-Emergency-Department-Attendances.xlsx). This app uses the Prophet functions both in the front-end and in the load script.

Finally, on your screenshot above, there is a second button which looks like it is being cut off due to your screen resolution. You can try zooming out (Ctrl + Mouse Scroll for Windows) or just hover over the object to be able to maximize it and use the second button.

**Comment by aljamo01** [comment]
@nabeel-oz That worked thank you!!
