### ISSUE TITLE
Association Rule Script Load Help

### ISSUE THREAD

**Issue by aghabdurauf** [nabeel-oz/qlik-py-tools#61]
![MBA Script load Association rule](https://user-images.githubusercontent.com/18259823/68024326-992dff80-fccb-11e9-8d7b-96e2b48784e1.PNG)

![MBA Product LHS error](https://user-images.githubusercontent.com/18259823/68024261-697ef780-fccb-11e9-8365-dfd71a7adb83.PNG)

Hello Nabeel,
I am using my own data with the same naming convention but the error occurs **'_PRODUCT LHS_' Not found**
Please help me out

Regards
Agha

**Comment by nabeel-oz** [comment]
Hi Agha, since the error occurs in less than a second I think you're trying to load from the sample app's QVD file. You need to set the variable for the IF condition in the load script to run the `PyTools.Association_Rules` function rather than the QVD file if you're using your own data.

If you're still facing problems please provide all the details requested in the issue template here: https://github.com/nabeel-oz/qlik-py-tools/blob/master/.github/ISSUE_TEMPLATE/2-exception-during-usage.md
