### ISSUE TITLE
Recommended Cloud GPU Instance for Faster Load

### ISSUE THREAD

**Issue by zerubroberts** [nabeel-oz/qlik-py-tools#74]
Hi Nabeel,

We have been trying to speed up the model training time for Deep Learning demos (Keras and Prophet Multivariate). Would you be able to recommend a gpu instance with deep learning libraries pre-installed, so that we could bring down the time to reload the Keras app to less than 5 minutes? 

So far, we've tried EC2 and paperspace and faced challenges setting up PyTools on Linux - is there a linux script available to initialize and run, instead of docker?

On the other hand, while choosing Windows, the apps only use cpu. Is there way to ensure that GPU is enabled on windows, for the apps to utilize it? 

Thank you very much.

**Comment by nabeel-oz** [comment]
Hi Zerub, 

I haven't tried a GPU instance for this, but there are a couple of things to note. 

First, you'll need to change the PyTools initialization script to install the GPU build of Tensorflow. The script installs the CPU version by default.

The demo app trains and tests 4 different neural networks. If you want to have a quicker demo for the training, you can just set up the app to train a single network. Simply remove the unwanted models from the `Estimators` and `Keras Architecture` tables in the load script under the `ML Config` section.

The testing is also time consuming due to walk forward validation, so you could reduce the test data as well. The app I've provided uses 6 months of test data. You can adjust the date range in the `Metrics & Predictions` section of the load script.

Finally, I haven't tried installing the SSE on Linux without Docker. Is there a reason why you can't use Docker? You can simply run a single container with vanilla Docker without an orchestration tool, and it makes the setup very simple.

**Comment by zerubroberts** [comment]
Thanks for the suggestions, Nabeel. We've been able to reduce the load time by selecting fewer models and trimming down the test data.
