### ISSUE TITLE
Linear regression

### ISSUE THREAD

**Issue by hammamr** [nabeel-oz/qlik-py-tools#92]
Hello,

I have just installed this extension on my laptop Windows 10 runnig in docker and QlikSense desktop.
It works fine and it's great!

But when I used this function  : PyTools.Prophet(Jour,Sum([vCPU utilisés]),'freq=D') to forcast the mesure [vCPU utilisés], the forcasted plot is varying a lot (see attched print screen)..
Is there a parameter to get a linear regression? or a plot with less variation?
![image](https://user-images.githubusercontent.com/41787890/75566047-5ac50900-5a4f-11ea-81d9-97aae41ec342.png)

Best regards.
Sidi Mahmoud

**Comment by nabeel-oz** [comment]
Hi Sidi,

Prophet has several parameters you could use to adjust as described here: https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Prophet.md.

For example, you could try setting a `cap` and `floor`. Or use the `take_log=true` argument and also try adjusting the `changepoint_prior_scale` argument. One thing to note is that you don't have sufficient data to detect longer term seasonality, which is one of the useful features of Prophet.

For results similar to a linear regression you can use the `return=trend` argument with Prophet. Otherwise you'll need to look at the capabilities described under the Machine Learning and Deep Learning sections.

**Comment by hammamr** [comment]
Hello Nabeel,
Thank you very much for the answer, il worked fine with the option return=trend.

PyTools.Prophet(Jour,Sum([vCPU utilisés]),'freq=D, return=trend')
![image](https://user-images.githubusercontent.com/41787890/75663745-9f2fef00-5c71-11ea-8b20-08290c2c8d07.png)

Best regards.
Sidi
