### ISSUE TITLE
Chatbot with sse?

### ISSUE THREAD

**Issue by sbeesm** [nabeel-oz/qlik-py-tools#96]
Hi,

Can the server-side-extension tools be used to implement a chatbot in Qlikview?

It wold work something like a user inputting a query in human language and charts populate the data accordingly. Query prediction/suggestion would be a plus point.
For example: Chart for sale of cars in Germany in year 2019 would populate a bar chart with 2019 car sales in Germany.

I guess the query suggestion part is the most tricky one to handle. Also, I can't think of the right Qlikview sheet object to handle such functionality.

Any idea how this can be done?

**Comment by nabeel-oz** [comment]
Hi @sbeesm 

The Server Side Extension protocol was developed to allow Qlik to call external calculation engines. This fits well with data science/ ML use cases, complex calculations and custom algorithms. Internally, Qlik is using a SSE for the GeoAnalytics connector implementation for Qlik Cloud Services.

A chat bot on the other hand, requires a way to call Qlik Sense or QlikView APIs, make use of NLP libraries and provide a chat UI for the user. I don't see how SSEs fit well with those capabilities. The [Qlik Insight Bot](https://help.qlik.com/en-US/insight-bot/Content/QlikInsightBot/Home.htm) is currently implemented in .NET and uses various Qlik Sense APIs to provide its capabilities.

Also, what you're describing is available out of the box in Qlik Sense through the Insight Advisor. So a modernization of the BI platform with Qlik Sense may be a worth considering rather than trying to build such 3rd generation BI capabilities in QlikView.

**Comment by sbeesm** [comment]
Actually I was looking for a solution which could be used in QlikView itself rather than moving to Qlik Sense. But your point is perfectly valid, I think SSE may not be the right set of tools to implement a chatbot. This can be better handled by Qlik Sense. 

So I guess I need to convince people at my company to move to Qlik Sense :') 
Anyways, thanks for sharing your thoughts on this.
